### PR TITLE
Add Ad Set Name to DcmCreativeAsset

### PR DESCRIPTION
**Pull request by allentsai**
We need ad set name for dcm creative assets for tracking.

### CODE REVIEW

**Comment by a37wong** [comment]
What was platform?

**Comment by allentsai** [comment]
@a37wong - platform was 'mobile' vs 'desktop' and was only used for the name.  We're removing this in favor of adSetName which will explicitly or implicitly provide that information. eg: w100_h100_pmobile vs MEDIUM_RECTANGLE (implied desktop)

**Comment by a37wong** [comment]
@allentsai Is this a dimension specifier?

**Comment by allentsai** [comment]
It's used for the names per https://docs.google.com/document/d/1tulXFH0hcVeV702S_AlWNMY9cc6tvBM5dbom1dmBYak/edit#heading=h.uc7zxxaf2pfv

**Comment by a37wong** [comment]
:+1:

**Pull request merged**
